
# ------------------------------------- Routes de navigation dans le site -------------------------

index:
    path: /{_locale}
    controller: App\Controller\PageController::index
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr


contact:
    path: /{_locale}/contact
    controller: App\Controller\PageController::contact
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr

boutique:
    path: /{_locale}/boutique
    controller: App\Controller\BoutiqueController::index
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr

rayon:
    path: /{_locale}/boutique/rayon/{id}
    controller: App\Controller\BoutiqueController::rayon
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr

chercher:
    path: /{_locale}/boutique/chercher
    controller: App\Controller\BoutiqueController::chercher
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr

# --------------------------------------- Routes pour panier ----------------------------------------------------
panier:
    path: /{_locale}/panier
    controller: App\Controller\PanierController::index
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr

panier_ajouter:
    path: /{_locale}/panier/ajouter/{idArticle}/{quantite}
    controller: App\Controller\PanierController::ajouter
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr

panier_enlever:
    path: /{_locale}/panier/enlever/{idArticle}/{quantite}
    controller: App\Controller\PanierController::enlever
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr

panier_supprimer:
    path: /{_locale}/panier/supprimer/{idArticle}
    controller: App\Controller\PanierController::supprimer
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr

panier_vider:
    path: /{_locale}/panier/vider
    controller: App\Controller\PanierController::vider
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr

#----------------------------------------------------------------------------------- Roles ---------------------------------------------------------------------------

usager_accueil:
    path: /{_locale}/usager
    controller: App\Controller\UsagerController::user
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr

admin_accueil:
    path: /{_locale}/admin
    controller: App\Controller\UsagerController::admin
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr

usager_inscription:
    path: /{_locale}/usager/inscription
    controller : App\Controller\UsagerController::new
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr


#------------------------------------------------------------------------ Authenticator ------------------------------------------------------

app_login:
    path: /{_locale}/login
    controller: App\Controller\SecurityController::login
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr

app_logout:
    path: /{_locale}/logout
    controller: App\Controller\SecurityController::logout
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr



#------------------------------------------------------------- Commandes --------------------------------------------------


creer_commande:
    path: /{_locale}/commande
    controller: App\Controller\PanierController::commande
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr



set_devise:
    path: /{_locale}/devise/{devise}
    controller: App\Controller\PageController::setDevise
    requirements:
        _locale: '%app.supported_locales%'
    defaults:
        _locale: fr
